---
on:
  push:
    branches:
      - develop

name: Deployment (stg)

jobs:
  deploy:
    name: Deployment (stg)
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: itk-dev/actions-remote-ssh@master
        with:
          command: |
            cd ${{ secrets.APP_PATH_STG }} &&
            chmod 755 html/sites/default &&
            git clean -d --force &&
            git checkout develop &&
            git fetch &&
            git reset origin/develop --hard
          host: ${{ secrets.HOST_STG }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}

      - name: Composer install
        uses: itk-dev/actions-remote-ssh@master
        with:
          command: |
            cd ${{ secrets.APP_PATH_STG }} &&
            chmod 755 html/sites/default &&
            composer1 install --no-dev
          host: ${{ secrets.HOST_STG }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}

      - name: Drush config import
        uses: itk-dev/actions-remote-ssh@master
        with:
          command: |
            cd ${{ secrets.APP_PATH_STG }} &&
            chmod 755 html/sites/default &&
            vendor/bin/drush cr --cache-clear &&
            vendor/bin/drush updb -y &&
            vendor/bin/drush config-import -y &&
            vendor/bin/drush cr --cache-clear
          host: ${{ secrets.HOST_STG }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}

      - name: Drush locale import
        uses: itk-dev/actions-remote-ssh@master
        with:
          command: |
            cd ${{ secrets.APP_PATH_STG }} &&
            chmod 755 html/sites/default &&
            vendor/bin/drush locale:import --type=customized --override=all da ../translations/custom-translations.da.po &&
            vendor/bin/drush cr --cache-clear
          host: ${{ secrets.HOST_STG }}
          key: ${{ secrets.PRIVATE_KEY }}
          cert: ${{ secrets.PUBLIC_KEY_CERT }}
